services:
  - type: web
    name: notebackend
    dir: osa3/notebackend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: notefrontend
    dir: osa2/kokrende
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://notebackend.onrender.com